spring.application.name: btvl-to-itag-and-iclp-translator
spring:
  batch:
    job:
      enabled: false
      name: btvlFileIngestionJob
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:sqlserver://127.0.0.1:1435;database=Apolloits_custom;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;
    username: ApolloViaplus
    password: 1sLI98!L&N%4vsN3d!30IdF1&VU9*NUOnl#CDp84GG**O@I1%9
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringBatchAdmin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 30
    generate-ddl: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus



## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
config:
  source-directory-path: C:\Users\ApolloViaplus\Downloads\CUSIOP_File_Samples\CUSIO_File_Samples\9002_0041_20240314055944_BTVL\
  source-file-name: 9002_0041_20240314055944_BTVL.txt